{
  "cells": [
    {
      "cell_type": "markdown",
      "source": [
        "## Compute Instance\n",
        "\n",
        "In this sample notebook, we will create a super basic model leveraging our Compute Instance.\n",
        "\n",
        "Leveraging an Azure ML Compute Instance we can train a model, and leverage it for prediction  \n",
        "\n",
        "After the model is created, what were the metrics of the model, how well did our model do on predictions, what data set was used for creating the model?  We don't have **traceablity** - but that is where Azure ML will come into play."
      ],
      "metadata": {}
    },
    {
      "cell_type": "code",
      "source": [
        "# Import libraries\n",
        "import pandas as pd\n",
        "import numpy as np\n",
        "import joblib\n",
        "import os\n",
        "from sklearn.model_selection import train_test_split\n",
        "from sklearn.linear_model import LogisticRegression\n",
        "from sklearn.metrics import roc_auc_score\n",
        "from sklearn.metrics import roc_curve\n",
        "\n",
        "\n",
        "diabetes = pd.read_parquet('./data/diabetes.parquet')\n",
        "diabetes.info()"
      ],
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": "<class 'pandas.core.frame.DataFrame'>\nRangeIndex: 10000 entries, 0 to 9999\nData columns (total 10 columns):\n #   Column                  Non-Null Count  Dtype  \n---  ------                  --------------  -----  \n 0   PatientID               10000 non-null  int64  \n 1   Pregnancies             10000 non-null  int64  \n 2   PlasmaGlucose           10000 non-null  int64  \n 3   DiastolicBloodPressure  10000 non-null  int64  \n 4   TricepsThickness        10000 non-null  int64  \n 5   SerumInsulin            10000 non-null  int64  \n 6   BMI                     10000 non-null  float64\n 7   DiabetesPedigree        10000 non-null  float64\n 8   Age                     10000 non-null  int64  \n 9   Diabetic                10000 non-null  int64  \ndtypes: float64(2), int64(8)\nmemory usage: 781.4 KB\n"
        }
      ],
      "execution_count": 1,
      "metadata": {
        "gather": {
          "logged": 1646886931242
        }
      }
    },
    {
      "cell_type": "code",
      "source": [
        "diabetes.describe()"
      ],
      "outputs": [
        {
          "output_type": "execute_result",
          "execution_count": 2,
          "data": {
            "text/plain": "          PatientID  Pregnancies  PlasmaGlucose  DiastolicBloodPressure  \\\ncount  1.000000e+04  10000.00000   10000.000000            10000.000000   \nmean   1.502122e+06      3.25580     107.850200               71.207500   \nstd    2.892868e+05      3.40572      31.920909               16.801478   \nmin    1.000038e+06      0.00000      44.000000               24.000000   \n25%    1.251672e+06      0.00000      84.000000               58.000000   \n50%    1.504394e+06      2.00000     105.000000               72.000000   \n75%    1.754608e+06      6.00000     129.000000               85.000000   \nmax    1.999997e+06     14.00000     192.000000              117.000000   \n\n       TricepsThickness  SerumInsulin           BMI  DiabetesPedigree  \\\ncount       10000.00000  10000.000000  10000.000000      10000.000000   \nmean           28.81760    139.243600     31.567022          0.400944   \nstd            14.50648    133.777919      9.804366          0.381463   \nmin             7.00000     14.000000     18.200807          0.078044   \n25%            15.00000     39.000000     21.247427          0.137065   \n50%            31.00000     85.000000     31.922421          0.199698   \n75%            41.00000    197.000000     39.328921          0.621158   \nmax            92.00000    796.000000     56.034628          2.301594   \n\n                Age      Diabetic  \ncount  10000.000000  10000.000000  \nmean      30.134100      0.334400  \nstd       12.106047      0.471804  \nmin       21.000000      0.000000  \n25%       22.000000      0.000000  \n50%       24.000000      0.000000  \n75%       35.000000      1.000000  \nmax       77.000000      1.000000  ",
            "text/html": "<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>PatientID</th>\n      <th>Pregnancies</th>\n      <th>PlasmaGlucose</th>\n      <th>DiastolicBloodPressure</th>\n      <th>TricepsThickness</th>\n      <th>SerumInsulin</th>\n      <th>BMI</th>\n      <th>DiabetesPedigree</th>\n      <th>Age</th>\n      <th>Diabetic</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>count</th>\n      <td>1.000000e+04</td>\n      <td>10000.00000</td>\n      <td>10000.000000</td>\n      <td>10000.000000</td>\n      <td>10000.00000</td>\n      <td>10000.000000</td>\n      <td>10000.000000</td>\n      <td>10000.000000</td>\n      <td>10000.000000</td>\n      <td>10000.000000</td>\n    </tr>\n    <tr>\n      <th>mean</th>\n      <td>1.502122e+06</td>\n      <td>3.25580</td>\n      <td>107.850200</td>\n      <td>71.207500</td>\n      <td>28.81760</td>\n      <td>139.243600</td>\n      <td>31.567022</td>\n      <td>0.400944</td>\n      <td>30.134100</td>\n      <td>0.334400</td>\n    </tr>\n    <tr>\n      <th>std</th>\n      <td>2.892868e+05</td>\n      <td>3.40572</td>\n      <td>31.920909</td>\n      <td>16.801478</td>\n      <td>14.50648</td>\n      <td>133.777919</td>\n      <td>9.804366</td>\n      <td>0.381463</td>\n      <td>12.106047</td>\n      <td>0.471804</td>\n    </tr>\n    <tr>\n      <th>min</th>\n      <td>1.000038e+06</td>\n      <td>0.00000</td>\n      <td>44.000000</td>\n      <td>24.000000</td>\n      <td>7.00000</td>\n      <td>14.000000</td>\n      <td>18.200807</td>\n      <td>0.078044</td>\n      <td>21.000000</td>\n      <td>0.000000</td>\n    </tr>\n    <tr>\n      <th>25%</th>\n      <td>1.251672e+06</td>\n      <td>0.00000</td>\n      <td>84.000000</td>\n      <td>58.000000</td>\n      <td>15.00000</td>\n      <td>39.000000</td>\n      <td>21.247427</td>\n      <td>0.137065</td>\n      <td>22.000000</td>\n      <td>0.000000</td>\n    </tr>\n    <tr>\n      <th>50%</th>\n      <td>1.504394e+06</td>\n      <td>2.00000</td>\n      <td>105.000000</td>\n      <td>72.000000</td>\n      <td>31.00000</td>\n      <td>85.000000</td>\n      <td>31.922421</td>\n      <td>0.199698</td>\n      <td>24.000000</td>\n      <td>0.000000</td>\n    </tr>\n    <tr>\n      <th>75%</th>\n      <td>1.754608e+06</td>\n      <td>6.00000</td>\n      <td>129.000000</td>\n      <td>85.000000</td>\n      <td>41.00000</td>\n      <td>197.000000</td>\n      <td>39.328921</td>\n      <td>0.621158</td>\n      <td>35.000000</td>\n      <td>1.000000</td>\n    </tr>\n    <tr>\n      <th>max</th>\n      <td>1.999997e+06</td>\n      <td>14.00000</td>\n      <td>192.000000</td>\n      <td>117.000000</td>\n      <td>92.00000</td>\n      <td>796.000000</td>\n      <td>56.034628</td>\n      <td>2.301594</td>\n      <td>77.000000</td>\n      <td>1.000000</td>\n    </tr>\n  </tbody>\n</table>\n</div>"
          },
          "metadata": {}
        }
      ],
      "execution_count": 2,
      "metadata": {
        "gather": {
          "logged": 1646886940397
        }
      }
    },
    {
      "cell_type": "code",
      "source": [
        "import matplotlib.pyplot as plt\n",
        "%matplotlib inline \n",
        "\n",
        "# Plot and log the count of diabetic vs non-diabetic patients\n",
        "diabetes = pd.read_parquet('./data/diabetes.parquet')\n",
        "\n",
        "diabetic_counts = diabetes['Diabetic'].value_counts()\n",
        "fig = plt.figure(figsize=(6,6))\n",
        "ax = fig.gca()    \n",
        "diabetic_counts.plot.bar(ax = ax) \n",
        "ax.set_title('Patients with Diabetes') \n",
        "ax.set_xlabel('Diagnosis') \n",
        "ax.set_ylabel('Patients')\n",
        "plt.show()"
      ],
      "outputs": [
        {
          "output_type": "stream",
          "name": "stderr",
          "text": "ERROR:root:Internal Python error in the inspect module.\nBelow is the traceback from this internal error.\n\nERROR:root:Internal Python error in the inspect module.\nBelow is the traceback from this internal error.\n\nERROR:root:Internal Python error in the inspect module.\nBelow is the traceback from this internal error.\n\n"
        },
        {
          "output_type": "stream",
          "name": "stdout",
          "text": "Traceback (most recent call last):\n  File \"/anaconda/envs/azureml_py36/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3343, in run_code\n    exec(code_obj, self.user_global_ns, self.user_ns)\n  File \"<ipython-input-3-055bdf3b34df>\", line 1, in <module>\n    import matplotlib.pyplot as plt\n  File \"/anaconda/envs/azureml_py36/lib/python3.6/site-packages/matplotlib/__init__.py\", line 1015, in <module>\n    rcParams = rc_params()\n  File \"/anaconda/envs/azureml_py36/lib/python3.6/site-packages/matplotlib/__init__.py\", line 878, in rc_params\n    return rc_params_from_file(matplotlib_fname(), fail_on_error)\n  File \"/anaconda/envs/azureml_py36/lib/python3.6/site-packages/matplotlib/__init__.py\", line 731, in matplotlib_fname\n    for fname in gen_candidates():\n  File \"/anaconda/envs/azureml_py36/lib/python3.6/site-packages/matplotlib/__init__.py\", line 720, in gen_candidates\n    yield os.path.join(os.getcwd(), 'matplotlibrc')\nFileNotFoundError: [Errno 2] No such file or directory\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/anaconda/envs/azureml_py36/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2044, in showtraceback\n    stb = value._render_traceback_()\nAttributeError: 'FileNotFoundError' object has no attribute '_render_traceback_'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/anaconda/envs/azureml_py36/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 1169, in get_records\n    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n  File \"/anaconda/envs/azureml_py36/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 316, in wrapped\n    return f(*args, **kwargs)\n  File \"/anaconda/envs/azureml_py36/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 350, in _fixed_getinnerframes\n    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n  File \"/anaconda/envs/azureml_py36/lib/python3.6/inspect.py\", line 1490, in getinnerframes\n    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n  File \"/anaconda/envs/azureml_py36/lib/python3.6/inspect.py\", line 1448, in getframeinfo\n    filename = getsourcefile(frame) or getfile(frame)\n  File \"/anaconda/envs/azureml_py36/lib/python3.6/inspect.py\", line 696, in getsourcefile\n    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n  File \"/anaconda/envs/azureml_py36/lib/python3.6/inspect.py\", line 725, in getmodule\n    file = getabsfile(object, _filename)\n  File \"/anaconda/envs/azureml_py36/lib/python3.6/inspect.py\", line 709, in getabsfile\n    return os.path.normcase(os.path.abspath(_filename))\n  File \"/anaconda/envs/azureml_py36/lib/python3.6/posixpath.py\", line 383, in abspath\n    cwd = os.getcwd()\nFileNotFoundError: [Errno 2] No such file or directory\nTraceback (most recent call last):\n  File \"/anaconda/envs/azureml_py36/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3343, in run_code\n    exec(code_obj, self.user_global_ns, self.user_ns)\n  File \"<ipython-input-3-055bdf3b34df>\", line 1, in <module>\n    import matplotlib.pyplot as plt\n  File \"/anaconda/envs/azureml_py36/lib/python3.6/site-packages/matplotlib/__init__.py\", line 1015, in <module>\n    rcParams = rc_params()\n  File \"/anaconda/envs/azureml_py36/lib/python3.6/site-packages/matplotlib/__init__.py\", line 878, in rc_params\n    return rc_params_from_file(matplotlib_fname(), fail_on_error)\n  File \"/anaconda/envs/azureml_py36/lib/python3.6/site-packages/matplotlib/__init__.py\", line 731, in matplotlib_fname\n    for fname in gen_candidates():\n  File \"/anaconda/envs/azureml_py36/lib/python3.6/site-packages/matplotlib/__init__.py\", line 720, in gen_candidates\n    yield os.path.join(os.getcwd(), 'matplotlibrc')\nFileNotFoundError: [Errno 2] No such file or directory\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/anaconda/envs/azureml_py36/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2044, in showtraceback\n    stb = value._render_traceback_()\nAttributeError: 'FileNotFoundError' object has no attribute '_render_traceback_'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/anaconda/envs/azureml_py36/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3263, in run_ast_nodes\n    if (await self.run_code(code, result,  async_=asy)):\n  File \"/anaconda/envs/azureml_py36/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3360, in run_code\n    self.showtraceback(running_compiled_code=True)\n  File \"/anaconda/envs/azureml_py36/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2047, in showtraceback\n    value, tb, tb_offset=tb_offset)\n  File \"/anaconda/envs/azureml_py36/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 1436, in structured_traceback\n    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n  File \"/anaconda/envs/azureml_py36/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 1336, in structured_traceback\n    self, etype, value, tb, tb_offset, number_of_lines_of_context\n  File \"/anaconda/envs/azureml_py36/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 1193, in structured_traceback\n    tb_offset)\n  File \"/anaconda/envs/azureml_py36/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 1150, in format_exception_as_a_whole\n    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n  File \"/anaconda/envs/azureml_py36/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 451, in find_recursion\n    return len(records), 0\nTypeError: object of type 'NoneType' has no len()\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/anaconda/envs/azureml_py36/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2044, in showtraceback\n    stb = value._render_traceback_()\nAttributeError: 'TypeError' object has no attribute '_render_traceback_'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/anaconda/envs/azureml_py36/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 1169, in get_records\n    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n  File \"/anaconda/envs/azureml_py36/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 316, in wrapped\n    return f(*args, **kwargs)\n  File \"/anaconda/envs/azureml_py36/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 350, in _fixed_getinnerframes\n    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n  File \"/anaconda/envs/azureml_py36/lib/python3.6/inspect.py\", line 1490, in getinnerframes\n    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n  File \"/anaconda/envs/azureml_py36/lib/python3.6/inspect.py\", line 1448, in getframeinfo\n    filename = getsourcefile(frame) or getfile(frame)\n  File \"/anaconda/envs/azureml_py36/lib/python3.6/inspect.py\", line 696, in getsourcefile\n    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n  File \"/anaconda/envs/azureml_py36/lib/python3.6/inspect.py\", line 725, in getmodule\n    file = getabsfile(object, _filename)\n  File \"/anaconda/envs/azureml_py36/lib/python3.6/inspect.py\", line 709, in getabsfile\n    return os.path.normcase(os.path.abspath(_filename))\n  File \"/anaconda/envs/azureml_py36/lib/python3.6/posixpath.py\", line 383, in abspath\n    cwd = os.getcwd()\nFileNotFoundError: [Errno 2] No such file or directory\nTraceback (most recent call last):\n  File \"/anaconda/envs/azureml_py36/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3343, in run_code\n    exec(code_obj, self.user_global_ns, self.user_ns)\n  File \"<ipython-input-3-055bdf3b34df>\", line 1, in <module>\n    import matplotlib.pyplot as plt\n  File \"/anaconda/envs/azureml_py36/lib/python3.6/site-packages/matplotlib/__init__.py\", line 1015, in <module>\n    rcParams = rc_params()\n  File \"/anaconda/envs/azureml_py36/lib/python3.6/site-packages/matplotlib/__init__.py\", line 878, in rc_params\n    return rc_params_from_file(matplotlib_fname(), fail_on_error)\n  File \"/anaconda/envs/azureml_py36/lib/python3.6/site-packages/matplotlib/__init__.py\", line 731, in matplotlib_fname\n    for fname in gen_candidates():\n  File \"/anaconda/envs/azureml_py36/lib/python3.6/site-packages/matplotlib/__init__.py\", line 720, in gen_candidates\n    yield os.path.join(os.getcwd(), 'matplotlibrc')\nFileNotFoundError: [Errno 2] No such file or directory\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/anaconda/envs/azureml_py36/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2044, in showtraceback\n    stb = value._render_traceback_()\nAttributeError: 'FileNotFoundError' object has no attribute '_render_traceback_'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/anaconda/envs/azureml_py36/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3263, in run_ast_nodes\n    if (await self.run_code(code, result,  async_=asy)):\n  File \"/anaconda/envs/azureml_py36/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3360, in run_code\n    self.showtraceback(running_compiled_code=True)\n  File \"/anaconda/envs/azureml_py36/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2047, in showtraceback\n    value, tb, tb_offset=tb_offset)\n  File \"/anaconda/envs/azureml_py36/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 1436, in structured_traceback\n    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n  File \"/anaconda/envs/azureml_py36/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 1336, in structured_traceback\n    self, etype, value, tb, tb_offset, number_of_lines_of_context\n  File \"/anaconda/envs/azureml_py36/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 1193, in structured_traceback\n    tb_offset)\n  File \"/anaconda/envs/azureml_py36/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 1150, in format_exception_as_a_whole\n    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n  File \"/anaconda/envs/azureml_py36/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 451, in find_recursion\n    return len(records), 0\nTypeError: object of type 'NoneType' has no len()\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/anaconda/envs/azureml_py36/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2044, in showtraceback\n    stb = value._render_traceback_()\nAttributeError: 'TypeError' object has no attribute '_render_traceback_'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/anaconda/envs/azureml_py36/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2895, in _run_cell\n    return runner(coro)\n  File \"/anaconda/envs/azureml_py36/lib/python3.6/site-packages/IPython/core/async_helpers.py\", line 68, in _pseudo_sync_runner\n    coro.send(None)\n  File \"/anaconda/envs/azureml_py36/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3072, in run_cell_async\n    interactivity=interactivity, compiler=compiler, result=result)\n  File \"/anaconda/envs/azureml_py36/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 3282, in run_ast_nodes\n    self.showtraceback()\n  File \"/anaconda/envs/azureml_py36/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2047, in showtraceback\n    value, tb, tb_offset=tb_offset)\n  File \"/anaconda/envs/azureml_py36/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 1436, in structured_traceback\n    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n  File \"/anaconda/envs/azureml_py36/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 1336, in structured_traceback\n    self, etype, value, tb, tb_offset, number_of_lines_of_context\n  File \"/anaconda/envs/azureml_py36/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 1211, in structured_traceback\n    chained_exceptions_tb_offset)\n  File \"/anaconda/envs/azureml_py36/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 1150, in format_exception_as_a_whole\n    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n  File \"/anaconda/envs/azureml_py36/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 451, in find_recursion\n    return len(records), 0\nTypeError: object of type 'NoneType' has no len()\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/anaconda/envs/azureml_py36/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2044, in showtraceback\n    stb = value._render_traceback_()\nAttributeError: 'TypeError' object has no attribute '_render_traceback_'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/anaconda/envs/azureml_py36/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 1169, in get_records\n    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n  File \"/anaconda/envs/azureml_py36/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 316, in wrapped\n    return f(*args, **kwargs)\n  File \"/anaconda/envs/azureml_py36/lib/python3.6/site-packages/IPython/core/ultratb.py\", line 350, in _fixed_getinnerframes\n    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n  File \"/anaconda/envs/azureml_py36/lib/python3.6/inspect.py\", line 1490, in getinnerframes\n    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n  File \"/anaconda/envs/azureml_py36/lib/python3.6/inspect.py\", line 1448, in getframeinfo\n    filename = getsourcefile(frame) or getfile(frame)\n  File \"/anaconda/envs/azureml_py36/lib/python3.6/inspect.py\", line 696, in getsourcefile\n    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n  File \"/anaconda/envs/azureml_py36/lib/python3.6/inspect.py\", line 725, in getmodule\n    file = getabsfile(object, _filename)\n  File \"/anaconda/envs/azureml_py36/lib/python3.6/inspect.py\", line 709, in getabsfile\n    return os.path.normcase(os.path.abspath(_filename))\n  File \"/anaconda/envs/azureml_py36/lib/python3.6/posixpath.py\", line 383, in abspath\n    cwd = os.getcwd()\nFileNotFoundError: [Errno 2] No such file or directory\n"
        }
      ],
      "execution_count": 3,
      "metadata": {
        "gather": {
          "logged": 1646886949253
        }
      }
    },
    {
      "cell_type": "code",
      "source": [
        "\n",
        "# Get the experiment run context\n",
        "\n",
        "# load the diabetes dataset\n",
        "print(\"Loading Data...\")\n",
        "diabetes = pd.read_parquet('./data/diabetes.parquet')\n",
        "\n",
        "# Separate features and labels\n",
        "X, y = diabetes[['Pregnancies','PlasmaGlucose','DiastolicBloodPressure','TricepsThickness','SerumInsulin','BMI','DiabetesPedigree','Age']].values, diabetes['Diabetic'].values\n",
        "\n",
        "# Split data into training set and test set\n",
        "X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=0)\n",
        "\n",
        "# Set regularization hyperparameter\n",
        "reg = 0.01\n",
        "\n",
        "# Train a logistic regression model\n",
        "print('Training a logistic regression model with regularization rate of', reg)\n",
        "model = LogisticRegression(C=1/reg, solver=\"liblinear\").fit(X_train, y_train)\n",
        "\n",
        "# calculate accuracy\n",
        "y_hat = model.predict(X_test)\n",
        "acc = np.average(y_hat == y_test)\n",
        "print('Accuracy:', acc)\n",
        "\n",
        "# calculate AUC\n",
        "y_scores = model.predict_proba(X_test)\n",
        "auc = roc_auc_score(y_test,y_scores[:,1])\n",
        "print('AUC: ' + str(auc))\n",
        "\n",
        "\n",
        "# Save the trained model in the outputs folder\n",
        "os.makedirs('outputs', exist_ok=True)\n",
        "joblib.dump(value=model, filename='outputs/diabetes_model.pkl')\n",
        "\n"
      ],
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": "Loading Data...\nTraining a logistic regression model with regularization rate of 0.01\nERROR! Session/line number was not unique in database. History logging moved to new session 46\nAccuracy: 0.774\nAUC: 0.8483203144435048\n"
        },
        {
          "output_type": "execute_result",
          "execution_count": 3,
          "data": {
            "text/plain": "['outputs/diabetes_model.pkl']"
          },
          "metadata": {}
        }
      ],
      "execution_count": 3,
      "metadata": {
        "gather": {
          "logged": 1646886958239
        }
      }
    },
    {
      "cell_type": "code",
      "source": [
        "predictions = model.predict(X_test)"
      ],
      "outputs": [],
      "execution_count": 4,
      "metadata": {
        "gather": {
          "logged": 1646886971341
        }
      }
    },
    {
      "cell_type": "code",
      "source": [
        "# Calculate model performance metrics\n",
        "from sklearn.metrics import classification_report\n",
        "\n",
        "report = classification_report(y_test, predictions)\n",
        "print(report)"
      ],
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": "              precision    recall  f1-score   support\n\n           0       0.80      0.87      0.84      1990\n           1       0.70      0.58      0.63      1010\n\n    accuracy                           0.77      3000\n   macro avg       0.75      0.73      0.73      3000\nweighted avg       0.77      0.77      0.77      3000\n\n"
        }
      ],
      "execution_count": 5,
      "metadata": {
        "gather": {
          "logged": 1646886979333
        }
      }
    },
    {
      "cell_type": "code",
      "source": [
        "# Confirm model can be reloaded from disk and will generate identical predictions\n",
        "\n",
        "filename = 'outputs/diabetes_model.pkl'\n",
        "loaded_model = joblib.load(filename)\n",
        "\n",
        "y_hat = loaded_model.predict(X_test)\n",
        "acc = np.average(y_hat == y_test)\n",
        "print('Accuracy:', acc)\n",
        "\n",
        "\n",
        "y_scores = loaded_model.predict_proba(X_test)\n",
        "auc = roc_auc_score(y_test,y_scores[:,1])\n",
        "print('AUC: ' + str(auc))\n"
      ],
      "outputs": [],
      "execution_count": null,
      "metadata": {}
    }
  ],
  "metadata": {
    "kernelspec": {
      "name": "python3-azureml",
      "language": "python",
      "display_name": "Python 3.6 - AzureML"
    },
    "language_info": {
      "name": "python",
      "version": "3.6.9",
      "mimetype": "text/x-python",
      "codemirror_mode": {
        "name": "ipython",
        "version": 3
      },
      "pygments_lexer": "ipython3",
      "nbconvert_exporter": "python",
      "file_extension": ".py"
    },
    "kernel_info": {
      "name": "python3-azureml"
    },
    "nteract": {
      "version": "nteract-front-end@1.0.0"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 0
}